"""
Base Embedding Provider Interface for Cortex AI.
Defines the abstract EmbeddingProvider class that all concrete vector embedding 
providers must implement.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List


class EmbeddingProvider(ABC):
    """
    Abstract Base Class (ABC) defining the interface for vector embedding models.
    
    Provides extensibility to support multiple vendors (Google, OpenAI, Ollama, HuggingFace).
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Returns the name of the embedding provider (e.g., 'Google Gemini')."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Returns the name of the model being utilized (e.g., 'models/text-embedding-004')."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Returns the length of vectors generated by this provider (e.g., 768)."""
        pass

    @abstractmethod
    def initialize_model(self) -> None:
        """
        Initializes the underlying model client.

        Raises:
            MissingAPIKeyException: If required API keys or credentials are not found.
            EmbeddingGenerationException: If the model client fails to instantiate.
        """
        pass

    @abstractmethod
    def embed_text(self, text: str) -> List[float]:
        """
        Queries the provider to generate a vector embedding for a single text.

        Args:
            text (str): Stripped and validated input text string.

        Returns:
            List[float]: Generated vector embedding coordinates.
        """
        pass

    @abstractmethod
    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """
        Queries the provider to generate vector embeddings for multiple text strings.

        Args:
            texts (List[str]): List of stripped and validated input text strings.

        Returns:
            List[List[float]]: List of generated vector embedding coordinates.
        """
        pass

    @abstractmethod
    def validate_embedding_dimension(self, vector: List[float]) -> bool:
        """
        Validates whether a vector length matches the expected model dimension.

        Args:
            vector (List[float]): Generated vector coordinates.

        Returns:
            bool: True if the dimension matches.
        """
        pass

    @abstractmethod
    def health_check(self) -> Dict[str, Any]:
        """
        Performs a diagnostic check verifying key presence, model status, and connectivity.

        Returns:
            Dict[str, Any]: Diagnostic report showing statuses for connectivity, 
                            key config, and model initialization.
        """
        pass
