"""
Gemini Embedding Provider for Cortex AI.
Implements the concrete GeminiEmbeddingProvider wrapping Google Generative AI 
Embeddings via LangChain.
"""

import logging
from typing import Any, Dict, List, Optional

from langchain_google_genai import GoogleGenerativeAIEmbeddings

from core.exceptions import (
    EmbeddingGenerationException,
    GeminiAPIException,
    MissingAPIKeyException,
)
from core.providers.base_embedding_provider import EmbeddingProvider
from utils.config import GOOGLE_API_KEY, DEFAULT_EMBEDDINGS_MODEL
from utils.logger import setup_logger

# Initialize logger
logger = setup_logger(__name__)

GEMINI_DIMENSION: int = 768


class GeminiEmbeddingProvider(EmbeddingProvider):
    """
    Concrete implementation of EmbeddingProvider using Google Gemini API.
    """

    def __init__(self, model_name: Optional[str] = None):
        """
        Initializes the GeminiEmbeddingProvider.

        Args:
            model_name (Optional[str]): Name of the Gemini embeddings model. 
                                        Defaults to DEFAULT_EMBEDDINGS_MODEL in config.py.
        """
        self._model_name = model_name if model_name is not None else DEFAULT_EMBEDDINGS_MODEL
        self.model: Optional[GoogleGenerativeAIEmbeddings] = None
        
        logger.debug(f"GeminiEmbeddingProvider initialized with model_name='{self._model_name}'")

    @property
    def provider_name(self) -> str:
        """Returns the name of the embedding provider."""
        return "Google Gemini"

    @property
    def model_name(self) -> str:
        """Returns the name of the model being utilized."""
        return self._model_name

    @property
    def dimension(self) -> int:
        """Returns the length of vectors generated by this provider (768)."""
        return GEMINI_DIMENSION

    def initialize_model(self) -> None:
        """
        Initializes the LangChain Google Generative AI Embeddings model client.

        Raises:
            MissingAPIKeyException: If GOOGLE_API_KEY is empty or not set.
            EmbeddingGenerationException: If the model failed to initialize.
        """
        if not GOOGLE_API_KEY:
            raise MissingAPIKeyException(
                "Missing GOOGLE_API_KEY. Please set the GOOGLE_API_KEY environment variable."
            )

        try:
            logger.info(f"Initializing GoogleGenerativeAIEmbeddings model with model_name='{self._model_name}'...")
            self.model = GoogleGenerativeAIEmbeddings(
                model=self._model_name,
                google_api_key=GOOGLE_API_KEY
            )
            logger.debug("GoogleGenerativeAIEmbeddings model client created successfully.")
        except Exception as e:
            raise EmbeddingGenerationException(f"Failed to initialize Gemini embedding model: {e}")

    def embed_text(self, text: str) -> List[float]:
        """
        Queries the Gemini API to generate a vector embedding for a single text.

        Args:
            text (str): Stripped and validated input text string.

        Returns:
            List[float]: Generated vector embedding coordinates.
        """
        if self.model is None:
            self.initialize_model()
            
        try:
            # We assert self.model is not None for type checking
            assert self.model is not None
            return self.model.embed_query(text)
        except Exception as e:
            raise GeminiAPIException(f"Gemini API single embedding call failed: {e}")

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """
        Queries the Gemini API to generate vector embeddings for multiple text strings.

        Args:
            texts (List[str]): List of stripped and validated input text strings.

        Returns:
            List[List[float]]: List of generated vector embedding coordinates.
        """
        if self.model is None:
            self.initialize_model()
            
        try:
            assert self.model is not None
            return self.model.embed_documents(texts)
        except Exception as e:
            raise GeminiAPIException(f"Gemini API batch embedding call failed: {e}")

    def validate_embedding_dimension(self, vector: List[float]) -> bool:
        """
        Validates whether a vector length matches the expected model dimension (768).

        Args:
            vector (List[float]): Generated vector coordinates.

        Returns:
            bool: True if the dimension matches.
        """
        if not vector:
            return False
        return len(vector) == self.dimension

    def health_check(self) -> Dict[str, Any]:
        """
        Performs a diagnostic check verifying key presence, model status, and connectivity.

        Returns:
            Dict[str, Any]: Structured report showing statuses.
        """
        api_key_configured = bool(GOOGLE_API_KEY)
        model_initialized = False
        connectivity = False
        details = "All checks passed."
        
        # 1. Test model client initialization
        if api_key_configured:
            try:
                if self.model is None:
                    self.initialize_model()
                model_initialized = True
            except Exception as e:
                details = f"Model initialization failed: {e}"
        else:
            details = "Missing GOOGLE_API_KEY in environment configuration."

        # 2. Test actual connectivity via simple ping text embedding if client is ready
        if model_initialized:
            try:
                # Use a lightweight word for connectivity ping test
                self.embed_text("ping")
                connectivity = True
            except Exception as e:
                details = f"Connection to Gemini API failed: {e}"

        all_ok = api_key_configured and model_initialized and connectivity
        
        return {
            "status": "healthy" if all_ok else "unhealthy",
            "provider": self.provider_name,
            "model": self.model_name,
            "checks": {
                "api_key_configured": api_key_configured,
                "model_initialized": model_initialized,
                "connectivity": connectivity
            },
            "details": details
        }
